
package GUI.Menu;

import GUI.GUIManager;
import GUI.Login.LoginGUI;
import GUI.Menu.Graphs.GraphBarChart;
import GUI.Menu.Graphs.GraphPieChart;

import javax.swing.*;
import java.awt.*;


/**
 * @author Mario
 */
public class HlavneMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form HlavneMenu
     */

    private GUIManager guiManager;
    private LoginGUI loginGUI;

    public HlavneMenuGUI(GUIManager guiManager, LoginGUI loginGUI) {
        initComponents2();
        this.guiManager = guiManager;
        this.loginGUI = loginGUI;
        this.displayGraph1();
        this.displayGraph2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents2() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HlavneMenuGUI");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("vezria: 1.0");

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Údržba poruchy");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_UDRZBA_PORUCHY_ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Stroje");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_STROJE_ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Zamestnanci");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_ZAMESTNANCI_ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Objednávky");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_OBJEDNAVKY_ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Nahlásenie poruchy");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_NAHLASENIE_PORUCHY_ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Logout");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LOGOUT_ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 153));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Náhradné diely");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NAHRADNE_DIELY_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1)
                                .addContainerGap(95, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton5)
                                                        .addComponent(jButton3)
                                                        .addComponent(jButton6)
                                                        .addComponent(jButton7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2)))
                                .addGap(30, 30, 30))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(jButton5)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)
                                .addGap(30, 30, 30)
                                .addComponent(jButton3)
                                .addGap(30, 30, 30)
                                .addComponent(jButton6)
                                .addGap(30, 30, 30)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(jLabel3))
                                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 300, 520);

        jPanel3.setBackground(new java.awt.Color(255, 255, 254));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(300, 0, 500, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void displayGraph1() {
        GraphPieChart graph = new GraphPieChart();
        graph.setPreferredSize(new Dimension(450, 225));
        graph.setBackground(new java.awt.Color(255, 255, 254));
        jPanel3.setLayout(new FlowLayout(FlowLayout.CENTER)); // Use FlowLayout to center the graph horizontally
        jPanel3.add(graph);
    }

    private void displayGraph2() {
        GraphBarChart graph = new GraphBarChart();
        graph.setPreferredSize(new Dimension(450, 225));
        graph.setBackground(new java.awt.Color(255, 255, 254));
        jPanel3.setLayout(new FlowLayout(FlowLayout.CENTER)); // Use FlowLayout to center the graph horizontally
        jPanel3.add(graph);
    }

    private void jButton1_UDRZBA_PORUCHY_ActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("S") || loginGUI.getRolaZam().equals("I") ) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazUdrzbuPoruchy();
        }
    }

    private void jButton2_NAHLASENIE_PORUCHY_ActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("S")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazPoruchu();
        }
    }

    private void jButton3_STROJE_ActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("S") || loginGUI.getRolaZam().equals("I") ) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazStoje();
        }
    }

    private void jButton6_OBJEDNAVKY_ActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("I") ) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazObjednavky();
        }
    }

    private void jButton5_ZAMESTNANCI_ActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (!loginGUI.getRolaZam().equals("A")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazTabulkuZam();
        }
    }

    private void jButton_NAHRADNE_DIELY_ActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("I")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazNahradneDiely();
        }
    }

    private void jButton_LOGOUT_ActionPerformed(java.awt.event.ActionEvent evt) {
        this.guiManager.odhlasenie();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
