/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.HlMenu2;

import GUI.GUIManager;
import GUI.HlMenu2.Reporty.ReportyOknoGUI;
import GUI.Login.LoginGUI;
import GUI.Menu.Graphs.GraphPieChart;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Mario
 */
public class HlMenuGUI extends javax.swing.JFrame {

    private GUIManager guiManager;
    private LoginGUI loginGUI;

    private String datumOd;
    private String datumDo;

    public HlMenuGUI(GUIManager guiManager, LoginGUI loginGUI) {
        initComponents();
        this.guiManager = guiManager;
        this.loginGUI = loginGUI;


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //jPanel1 = new javax.swing.JPanel();
        jButtonZamestnanci = new javax.swing.JButton();
        jButtonObjednavky = new javax.swing.JButton();
        jButtonNahlasenie = new javax.swing.JButton();
        jButtonPoruchy = new javax.swing.JButton();
        jButtonNahradneDiely = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonStroje = new javax.swing.JButton();
        jButtonReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jButtonZamestnanci.setBorder(null);
        jButtonZamestnanci.setBackground(new Color(255,255,254));

        // Load the image from file
        ImageIcon iconZam = new ImageIcon("res\\zamestnanci2.png");
        // Set the icon on the JButton
        jButtonZamestnanci.setIcon(iconZam);
        jButtonZamestnanci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZamestnanciActionPerformed(evt);
            }
        });

        jButtonObjednavky.setBorder(null);
        // Load the image from file
        ImageIcon iconObj = new ImageIcon("res\\objednavky2.png");
        // Set the icon on the JButton
        jButtonObjednavky.setIcon(iconObj);
        jButtonObjednavky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObjednavkyActionPerformed(evt);
            }
        });

        jButtonNahlasenie.setBorder(null);
        // Load the image from file
        ImageIcon iconNahlasenie = new ImageIcon("res\\nahlasenia2.png");
        // Set the icon on the JButton
        jButtonNahlasenie.setIcon(iconNahlasenie);
        jButtonNahlasenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNahlasenieActionPerformed(evt);
            }
        });

        jButtonPoruchy.setBorder(null);
        // Load the image from file
        ImageIcon iconPoruchy = new ImageIcon("res\\poruchy2.png");
        // Set the icon on the JButton
        jButtonPoruchy.setIcon(iconPoruchy);
        jButtonPoruchy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPoruchyActionPerformed(evt);
            }
        });

        jButtonNahradneDiely.setBorder(null);
        // Load the image from file
        ImageIcon iconND = new ImageIcon("res\\ND2.png");
        // Set the icon on the JButton
        jButtonNahradneDiely.setIcon(iconND);
        jButtonNahradneDiely.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNahradneDielyActionPerformed(evt);
            }
        });

        jButtonLogout.setBorder(null);
        // Load the image from file
        ImageIcon iconlogout = new ImageIcon("res\\logout2.png");
        // Set the icon on the JButton
        jButtonLogout.setIcon(iconlogout);
        //jButtonLogout.setBackground(new Color(230,230,230));
        jButtonLogout.setBackground(new Color(96,108,199));

        //jButtonLogout.setFocusPainted(false);
        jButtonLogout.setContentAreaFilled(false);
        //jButtonLogout.setBorderPainted(false);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonStroje.setBorder(null);
        jButtonStroje.setBackground(new Color(255,255,254));
        // Load the image from file
        ImageIcon iconStroje = new ImageIcon("res\\Stroje2.png");
        // Set the icon on the JButton
        jButtonStroje.setIcon(iconStroje);
        jButtonStroje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStrojeActionPerformed(evt);
            }
        });

        jButtonReport.setText("REPORTY");
        jButtonReport.setBorder(null);
        jButtonReport.setBackground(new Color(255,255,254));
        jButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonReportActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        ImageIcon iconPozadie = new ImageIcon("res/menu_pozadie4.png");
        ImagePanel jPanel1 = new ImagePanel(iconPozadie);
        jPanel1.setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(94, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonZamestnanci, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jButtonStroje, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonObjednavky, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonPoruchy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonNahlasenie, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(jButtonNahradneDiely, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonPoruchy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonZamestnanci, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNahlasenie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonStroje, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonObjednavky, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonNahradneDiely, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                        .addComponent(jButtonReport, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonZamestnanci.setBorderPainted(false);
        jButtonZamestnanci.setFocusPainted(false);
        jButtonZamestnanci.setContentAreaFilled(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZamestnanciActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (!loginGUI.getRolaZam().equals("A")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazTabulkuZam();
        }
    }

    private void jButtonPoruchyActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("S") || loginGUI.getRolaZam().equals("I")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazUdrzbuPoruchy();
        }
    }

    private void jButtonNahlasenieActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("S")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazPoruchu();
        }
    }

    private void jButtonStrojeActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("S") || loginGUI.getRolaZam().equals("I")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazStoje();
        }
    }

    private void jButtonObjednavkyActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (!loginGUI.getRolaZam().equals("S") && !loginGUI.getRolaZam().equals("A")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazObjednavky();
        }
    }

    private void jButtonNahradneDielyActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(loginGUI.getRolaZam() + " - TU SOM");
        if (loginGUI.getRolaZam().equals("I")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazNahradneDiely();
        }
    }

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {
        this.guiManager.odhlasenie();
    }

    private void jButtonReportActionPerformed(java.awt.event.ActionEvent evt) throws IOException, InterruptedException {
        // TODO add your handling code here:
        if (!loginGUI.getRolaZam().equals("A")) {
            JOptionPane.showMessageDialog(null, "Na túto operáciu nemáte povolenie!");
        } else {
            this.guiManager.zobrazenieReportOkno();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonNahlasenie;
    private javax.swing.JButton jButtonNahradneDiely;
    private javax.swing.JButton jButtonObjednavky;
    private javax.swing.JButton jButtonPoruchy;
    private javax.swing.JButton jButtonStroje;
    private javax.swing.JButton jButtonZamestnanci;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButtonReport;
    // End of variables declaration//GEN-END:variables
}
