
package GUI.Login;

import GUI.GUIManager;
import Sifrovanie.PasswordUtils;
import Tabulky.BZamestnanec;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.*;
import java.awt.*;
import java.math.BigInteger;

/**
 * @author Mario
 */

public class LoginGUI extends javax.swing.JFrame {
    //public static boolean prihlasenie = false;

    /**
     * Creates new form Login
     */

    private BigInteger osCisloLogin;
    private String rola;
    private GUIManager guiManager;
    private String cisloHaly;
    private LoginListener loginListener;

    EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("default");
    EntityManager entityManager = entityManagerFactory.createEntityManager();

    public LoginGUI(GUIManager guiManager) {
        initComponents();
        this.guiManager = guiManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonPrihlasenie = new javax.swing.JButton();
        jButtonZabudnute = new javax.swing.JButton();
        Right = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setMinimumSize(new java.awt.Dimension(400, 500));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Osobné číslo");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Heslo");

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N


        jButtonPrihlasenie.setBackground(new java.awt.Color(255, 204, 153));
        jButtonPrihlasenie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonPrihlasenie.setText("Prihlásiť sa");
        jButtonPrihlasenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrihlasenieActionPerformed(evt);
            }
        });

        jButtonZabudnute.setBackground(new java.awt.Color(255, 255, 254));
        jButtonZabudnute.setText("Zabudnuté prihlasovacie údaje?");
        jButtonZabudnute.setBorder(null);

        jButtonZabudnute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZabudnuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
                LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LeftLayout.createSequentialGroup()
                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(LeftLayout.createSequentialGroup()
                                                .addGap(144, 144, 144)
                                                .addComponent(jLabel1))
                                        .addGroup(LeftLayout.createSequentialGroup()
                                                .addGap(137, 137, 137)
                                                .addComponent(jButtonPrihlasenie))
                                        .addGroup(LeftLayout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jTextField1)
                                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                                        .addComponent(jLabel3)))
                                        .addGroup(LeftLayout.createSequentialGroup()
                                                .addGap(115, 115, 115)
                                                .addComponent(jButtonZabudnute)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
                LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LeftLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButtonPrihlasenie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(jButtonZabudnute)
                                .addGap(30, 30, 30))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 400, 500);

        Right.setBackground(new java.awt.Color(255, 204, 153));
        Right.setMinimumSize(new java.awt.Dimension(400, 500));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        // Load the image from file
        ImageIcon originalIcon = new ImageIcon("C:\\Users\\Mario\\Desktop\\bakalarka\\hibernate_bakalarka\\H_bakalarka\\icons\\login_logo.png");

        // Resize the image to the desired size
        Image scaledImage = originalIcon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);

        // Create a new ImageIcon with the scaled image
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Set the scaled icon on the JLabel
        jLabel5.setIcon(scaledIcon);

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
                RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RightLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(42, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
                RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RightLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public BigInteger getOsCisloLogin() {
        return osCisloLogin;
    }

    public String getRolaZam() {
        return rola;
    }

    public String getCisloHaly() {
        return cisloHaly;
    }

    public void setLoginListener(LoginListener listener) {
        this.loginListener = listener;
    }

    // Method called after successful login
    private void onLoginSuccess() {
        if (loginListener != null) {
            loginListener.onLoginSuccess();
        }
    }

    private void jButtonPrihlasenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrihlasenieActionPerformed
        // Získajte hodnoty zo vstupných polí
        try {
            String osobneCisloText = jTextField1.getText().trim(); // Trim to remove leading/trailing whitespaces
            if (osobneCisloText.isEmpty()) {
                throw new NumberFormatException();  // Throw exception for empty input
            }
            int osobneCislo = Integer.parseInt(jTextField1.getText());
            String zadaneHeslo = new String(jPasswordField1.getPassword());

            if (osobneCislo <= 0 || zadaneHeslo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Zle vyplnené prihlasovacie údaje!", "Chyba pri prihlásení", JOptionPane.ERROR_MESSAGE);
            } else {

                // Príklad výpisu hodnôt pre overenie
                //System.out.println("Osobné číslo: " + osobneCislo);
                //System.out.println("Heslo: " + zadaneHeslo);

                PasswordUtils pu = new PasswordUtils();
                String dobreHeslo = pu.vratHesloVseobecne(osobneCislo);

                if (PasswordUtils.checkPassword(zadaneHeslo, dobreHeslo)) {

                    this.osCisloLogin = BigInteger.valueOf(osobneCislo);
                    BZamestnanec zam = entityManager.find(BZamestnanec.class, osCisloLogin);
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                    this.rola = zam.getTypZamD();
                    this.cisloHaly = zam.getPracoviskoD();
                    this.onLoginSuccess();
                    guiManager.zobrazHlavneMenu();
                } else {
                    // Nespravne prihlasovacie udaje
                    JOptionPane.showMessageDialog(this, "Zadali ste nesprávne prihlasovacie údaje!", "Chyba pri prihlásení", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Zle vyplnené prihlasovacie údaje!", "Chyba pri prihlásení", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonPrihlasenieActionPerformed

    private void jButtonZabudnuteActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Kontaktujte svojho nadriadeného, pre resetovanie prihlasovacích údajov!", "Zabudnuté prihlasovacie údaje", JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Right;
    private javax.swing.JButton jButtonPrihlasenie;
    private javax.swing.JButton jButtonZabudnute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
